// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Api.Data;

#nullable disable

namespace Stock.Api.Data.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260730203733_Restricciones")]
    partial class Restricciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.Api.Data.Views.StockActualView", b =>
                {
                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_StockActual", (string)null);
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Articulo", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticuloId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Modern_Spanish_CI_AS");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Modern_Spanish_CI_AI");

                    b.Property<decimal>("Margen")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("CAST([PrecioCosto] * (1 + [Margen] / 100.0) AS decimal(18,2))", true);

                    b.Property<int>("PuntoPedido")
                        .HasColumnType("int");

                    b.Property<int>("StockIdeal")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("ArticuloId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_Articulo_Codigo");

                    b.ToTable("Articulo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Articulo_OrdenDeStocks", "[StockMinimo] <= [PuntoPedido] AND [PuntoPedido] <= [StockIdeal]");

                            t.HasCheckConstraint("CK_Articulo_ValoresNoNegativos", "[PrecioCosto] >= 0 AND [Margen] >= 0 AND [StockMinimo] >= 0 AND [PuntoPedido] >= 0 AND [StockIdeal] >= 0");
                        });
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorId"));

                    b.Property<DateTime>("ErrorDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ErrorId");

                    b.ToTable("ErrorLog", (string)null);
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("Numero");

                    b.ToTable("Movimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movimiento_Tipo", "[Tipo] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.MovimientoDetalle", b =>
                {
                    b.Property<int>("MovimientoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoDetalleId"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoNumero")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("CAST([Cantidad] * [PrecioUnitario] AS decimal(18,2))", true);

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovimientoDetalleId");

                    b.HasIndex("ArticuloId")
                        .HasDatabaseName("IX_MovimientoDetalle_ArticuloId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ArticuloId"), new[] { "Cantidad", "MovimientoNumero" });

                    b.HasIndex("MovimientoNumero")
                        .HasDatabaseName("IX_MovimientoDetalle_MovimientoNumero");

                    b.ToTable("MovimientoDetalle", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovimientoDetalle_Cantidad", "[Cantidad] > 0 AND [Cantidad] <= 1000000");

                            t.HasCheckConstraint("CK_MovimientoDetalle_PrecioUnitario", "[PrecioUnitario] >= 0");
                        });
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("PerfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("PerfilId");

                    b.HasIndex("EsAdministrador")
                        .IsUnique()
                        .HasDatabaseName("UX_Perfil_EsAdministrador")
                        .HasFilter("[EsAdministrador] = 1");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuario_NombreUsuario");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("IX_Usuario_PerfilId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.MovimientoDetalle", b =>
                {
                    b.HasOne("Stock.Api.Domain.Entities.Articulo", "Articulo")
                        .WithMany("Detalle")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Stock.Api.Domain.Entities.Movimiento", "Movimiento")
                        .WithMany("Detalle")
                        .HasForeignKey("MovimientoNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Stock.Api.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Articulo", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Movimiento", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("Stock.Api.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
